export const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const USER = {
    CREATE: 'USER_CREATE',
    CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    CREATE_FAILURE: 'USER_CREATE_FAILURE',

    READ: 'USER_READ',
    READ_SUCCESS: 'USER_READ_SUCCESS',
    READ_FAILURE: 'USER_READ_FAILURE',

    READALL: 'USER_READALL',
    READALL_SUCCESS: 'USER_READALL_SUCCESS',
    READALL_FAILURE: 'USER_READALL_FAILURE',

    UPDATE: 'USER_UPDATE',
    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

    DELETE: 'USER_DELETE',
    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE'    
}

export const ALERT = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    CLEAR: 'CLEAR'
}

export const LOADING = {
    LOADING: 'LOADING',
    SUCCESS: 'LOADING_SUCCESS',
    FAILURE: 'LOADING_FAILURE',
    CLEAR: 'LOADING_CLEAR'
}