//================================================= user
export const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const USER = {
    CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    CREATE_FAILURE: 'USER_CREATE_FAILURE',

    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

    GET_SUCCESS:    'USER_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'USER_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'USER_GETDROPDOWN_SUCCESS',

    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE'    
}

export const ROLE = {
    CREATE_SUCCESS: 'ROLE_CREATE_SUCCESS',
    CREATE_FAILURE: 'ROLE_CREATE_FAILURE',

    UPDATE_SUCCESS: 'ROLE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'ROLE_UPDATE_FAILURE',

    GET_SUCCESS: 'ROLE_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'ROLE_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'ROLE_GETDROPDOWN_SUCCESS',

    DELETE_SUCCESS: 'ROLE_DELETE_SUCCESS',
    DELETE_FAILURE: 'ROLE_DELETE_FAILURE'    
}

export const COMMONITEM = {
    CREATE_SUCCESS: 'COMMONITEM_CREATE_SUCCESS',
    CREATE_FAILURE: 'COMMONITEM_CREATE_FAILURE',

    UPDATE_SUCCESS: 'COMMONITEM_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'COMMONITEM_UPDATE_FAILURE',

    GET_SUCCESS: 'COMMONITEM_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'COMMONITEM_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'COMMONITEM_GETDROPDOWN_SUCCESS',

    DELETE_SUCCESS: 'COMMONITEM_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMMONITEM_DELETE_FAILURE'    
}

//================================================= company
export const IMAGE = {
    CREATE_SUCCESS: 'IMAGE_CREATE_SUCCESS',
    CREATE_FAILURE: 'IMAGE_CREATE_FAILURE',

    UPDATE_SUCCESS: 'IMAGE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'IMAGE_UPDATE_FAILURE',

    GET_SUCCESS: 'IMAGE_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'IMAGE_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'IMAGE_GETDROPDOWN_SUCCESS',

    DELETE_SUCCESS: 'IMAGE_DELETE_SUCCESS',
    DELETE_FAILURE: 'IMAGE_DELETE_FAILURE'    
}

//================================================= company
export const COMPANY = {
    CREATE_SUCCESS: 'COMPANY_CREATE_SUCCESS',
    CREATE_FAILURE: 'COMPANY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'COMPANY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'COMPANY_UPDATE_FAILURE',

    GET_SUCCESS: 'COMPANY_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'COMPANY_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'COMPANY_GETDROPDOWN_SUCCESS',


    DELETE_SUCCESS: 'COMPANY_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMPANY_DELETE_FAILURE'    
}

export const REGION = {
    CREATE_SUCCESS: 'REGION_CREATE_SUCCESS',
    CREATE_FAILURE: 'REGION_CREATE_FAILURE',

    UPDATE_SUCCESS: 'REGION_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'REGION_UPDATE_FAILURE',

    GET_SUCCESS: 'REGION_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'REGION_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'REGION_GETDROPDOWN_SUCCESS',   

    DELETE_SUCCESS: 'REGION_DELETE_SUCCESS',
    DELETE_FAILURE: 'REGION_DELETE_FAILURE'    
}

//================================================= product
export const PRODUCT = {
    CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    CREATE_FAILURE: 'PRODUCT_CREATE_FAILURE',

    UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',

    GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'PRODUCT_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'PRODUCT_GETDROPDOWN_SUCCESS',    

    DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    DELETE_FAILURE: 'PRODUCT_DELETE_FAILURE'    
}

export const CATEGORY = {
    CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
    CREATE_FAILURE: 'CATEGORY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CATEGORY_UPDATE_FAILURE',

    GET_SUCCESS: 'CATEGORY_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'CATEGORY_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'CATEGORY_GETDROPDOWN_SUCCESS',   

    DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
    DELETE_FAILURE: 'CATEGORY_DELETE_FAILURE'    
}

export const PRODUCTPURCHASE = {
    CREATE_SUCCESS: 'PRODUCTPURCHASE_CREATE_SUCCESS',
    CREATE_FAILURE: 'PRODUCTPURCHASE_CREATE_FAILURE',

    UPDATE_SUCCESS: 'PRODUCTPURCHASE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PRODUCTPURCHASE_UPDATE_FAILURE',

    GET_SUCCESS: 'PRODUCTPURCHASE_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'PRODUCTPURCHASE_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'PRODUCTPURCHASE_GETDROPDOWN_SUCCESS',    

    DELETE_SUCCESS: 'PRODUCTPURCHASE_DELETE_SUCCESS',
    DELETE_FAILURE: 'PRODUCTPURCHASE_DELETE_FAILURE'    
}

//================================================= COMMODITY

export const COMMODITY = {
    CREATE_SUCCESS: 'COMMODITY_CREATE_SUCCESS',
    CREATE_FAILURE: 'COMMODITY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'COMMODITY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'COMMODITY_UPDATE_FAILURE',

    GET_SUCCESS: 'COMMODITY_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'COMMODITY_GETBYSEARCH_SUCCESS',
    GETBYSEARCH_GETCOMMODITY_SUCCESS: 'COMMODITY_GETBYSEARCH_GETCOMMODITY_SUCCESS',
    GETBYSEARCH_GETPRODUCT_SUCCESS: 'COMMODITY_GETBYSEARCH_GETPRODUCT_SUCCESS',
    
    GETDROPDOWN_SUCCESS: 'COMMODITY_GETDROPDOWN_SUCCESS',    

    DELETE_SUCCESS: 'COMMODITY_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMMODITY_DELETE_FAILURE'    
}



export const ALERT = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    INFO: 'INFO',
    NOTIFY: 'NOTIFY',
    CLEAR: 'CLEAR',
}

export const LOADING = {
    LOADING: 'LOADING',
    SUCCESS: 'LOADING_SUCCESS',
    FAILURE: 'LOADING_FAILURE',
    CLEAR: 'LOADING_CLEAR'
}

// rostercontact, bankaccount, 
export const FACELESS = {
    FACELESS_SUCCESS: 'FACELESS_CREATE_SUCCESS',
    FACELESS_FAILURE: 'CATEGORY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'FACELESS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'FACELESS_UPDATE_FAILURE',

    GET_SUCCESS: 'FACELESS_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'FACELESS_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'FACELESS_GETDROPDOWN_SUCCESS',   

    DELETE_SUCCESS: 'FACELESS_DELETE_SUCCESS',
    DELETE_FAILURE: 'FACELESS_DELETE_FAILURE'    
}