//================================================= user
export const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const USER = {
    CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    CREATE_FAILURE: 'USER_CREATE_FAILURE',

    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

    GET_SUCCESS:    'USER_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'USER_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'USER_GETDROPDOWN_SUCCESS',

    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE'    
}

export const ROLE = {
    CREATE_SUCCESS: 'ROLE_CREATE_SUCCESS',
    CREATE_FAILURE: 'ROLE_CREATE_FAILURE',

    UPDATE_SUCCESS: 'ROLE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'ROLE_UPDATE_FAILURE',

    GET_SUCCESS: 'ROLE_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'ROLE_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'ROLE_GETDROPDOWN_SUCCESS',

    DELETE_SUCCESS: 'ROLE_DELETE_SUCCESS',
    DELETE_FAILURE: 'ROLE_DELETE_FAILURE'    
}
//================================================= company
export const COMPANY = {
    CREATE_SUCCESS: 'COMPANY_CREATE_SUCCESS',
    CREATE_FAILURE: 'COMPANY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'COMPANY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'COMPANY_UPDATE_FAILURE',

    GET_SUCCESS: 'COMPANY_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'COMPANY_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'COMPANY_GETDROPDOWN_SUCCESS',


    DELETE_SUCCESS: 'COMPANY_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMPANY_DELETE_FAILURE'    
}

//================================================= product
export const PRODUCT = {
    CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    CREATE_FAILURE: 'PRODUCT_CREATE_FAILURE',

    UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',

    GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'PRODUCT_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'PRODUCT_GETDROPDOWN_SUCCESS',    

    DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    DELETE_FAILURE: 'PRODUCT_DELETE_FAILURE'    
}

export const CATEGORY = {
    CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
    CREATE_FAILURE: 'CATEGORY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CATEGORY_UPDATE_FAILURE',

    GET_SUCCESS: 'CATEGORY_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'CATEGORY_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'CATEGORY_GETDROPDOWN_SUCCESS',   

    DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
    DELETE_FAILURE: 'CATEGORY_DELETE_FAILURE'    
}








export const ALERT = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    INFO: 'INFO',
    NOTIFY: 'NOTIFY',
    CLEAR: 'CLEAR',
}

export const LOADING = {
    LOADING: 'LOADING',
    SUCCESS: 'LOADING_SUCCESS',
    FAILURE: 'LOADING_FAILURE',
    CLEAR: 'LOADING_CLEAR'
}
export const FACELESS = {
    FACELESS_SUCCESS: 'FACELESS_CREATE_SUCCESS',
    FACELESS_FAILURE: 'CATEGORY_CREATE_FAILURE',

    UPDATE_SUCCESS: 'FACELESS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'FACELESS_UPDATE_FAILURE',

    GET_SUCCESS: 'FACELESS_GET_SUCCESS',
    GETBYSEARCH_SUCCESS: 'FACELESS_GETBYSEARCH_SUCCESS',
    GETDROPDOWN_SUCCESS: 'FACELESS_GETDROPDOWN_SUCCESS',   

    DELETE_SUCCESS: 'FACELESS_DELETE_SUCCESS',
    DELETE_FAILURE: 'FACELESS_DELETE_FAILURE'    
}