export const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const USER = {
    CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    CREATE_FAILURE: 'USER_CREATE_FAILURE',

    GET_SUCCESS: 'USER_GET_SUCCESS',
    GET_FAILURE: 'USER_GET_FAILURE',

    GETALL_SUCCESS: 'USER_GETALL_SUCCESS',
    GETALL_FAILURE: 'USER_GETALL_FAILURE',

    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE'    
}

export const ROLE = {
    CREATE_SUCCESS: 'ROLE_CREATE_SUCCESS',
    CREATE_FAILURE: 'ROLE_CREATE_FAILURE',

    GET_SUCCESS: 'ROLE_GET_SUCCESS',
    GET_FAILURE: 'ROLE_GET_FAILURE',

    GETALL_SUCCESS: 'ROLE_GETALL_SUCCESS',
    GETALL_FAILURE: 'ROLE_GETALL_FAILURE',

    UPDATE_SUCCESS: 'ROLE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'ROLE_UPDATE_FAILURE',

    DELETE_SUCCESS: 'ROLE_DELETE_SUCCESS',
    DELETE_FAILURE: 'ROLE_DELETE_FAILURE'    
}

export const ALERT = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    INFO: 'INFO',
    NOTIFY: 'NOTIFY',
    CLEAR: 'CLEAR',
}

export const LOADING = {
    LOADING: 'LOADING',
    SUCCESS: 'LOADING_SUCCESS',
    FAILURE: 'LOADING_FAILURE',
    CLEAR: 'LOADING_CLEAR'
}